# frozen_string_literal: true

ADMIN_EMAIL = 'customer.service@fmadata.com'
ADMIN_SITE = ''
BRIAN_EMAIL = 'brian.long@fmadata.com'
COMPANY_AKA = 'validators.app'
FMA = 'validators.app'
FMA_LLC = 'validators.app'
OUR_CITY_STATE_ZIP = 'Boulder, CO 80302-3812'
OUR_COMPANY = ''
OUR_EMAIL_ADDRESS = ''
OUR_FAX = '(303) 443-2073'
OUR_LOGO = ''
OUR_STREET_ADDRESS = '2575 PEARL ST STE 230'
OUR_TELEPHONE = '(303) 443-2070'
THIS_SITE = 'www.validators.app'
THIS_HOST = 'validators.app'
