json.extract! stake_account,
  :id,
  :activation_epoch,
  :active_stake,
  :delegated_stake,
  :delegated_vote_account_address,
  :stake_pubkey,
  :staker,
  :withdrawer,
  :stake_pool_id,
  :network,
  :batch_uuid,
  :formatted_delegated_stake
