# The master.key file is not kept in our Git repo. There are certain
# constants required for this application. These are examples.
#
#   EDITOR=vim rails credentials:edit
#
# Use `rails secret` to create a new secret_key_base in your console and copy
# the key here.
secret_key_base: x


# Use a 32-bit attribute_key. Run this in a Rails console to get a new key:
#   `rake secret`[0..31]
#    => "651c47533d0e85516346c26ade74ab40" # Don't use this key!
attribute_key: x

# We are using a font set from https://fontawesome.com/ and you can get a free
# download key there.
font_awesome_download_key: x

# If you are using AWS S3 for file storage
aws:
  access_key_id: 123
  secret_access_key: 345
  region: X
  bucket: X

# If you are using Vault
vault:
  application: X
  address: X
  token: X
