---
:daemon: false
# :verbose: true
# :concurrency: 5
# :timeout: 30
development:
  :concurrency: 4
stage:
  :concurrency: 4
production:
  :concurrency: 6
:queues:
  - high_priority
  - default
  - low_priority
  - lowest_priority
