# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: geyser.proto for package 'geyser'

require 'grpc'
require 'geyser_pb'

module Geyser
  module Geyser
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'geyser.Geyser'

      rpc :Subscribe, stream(::Geyser::SubscribeRequest), stream(::Geyser::SubscribeUpdate)
      rpc :SubscribeDeshred, stream(::Geyser::SubscribeDeshredRequest), stream(::Geyser::SubscribeUpdateDeshred)
      rpc :SubscribeGossip, ::Geyser::SubscribeGossipRequest, stream(::Geyser::SubscribeUpdateGossip)
      rpc :SubscribeReplayInfo, ::Geyser::SubscribeReplayInfoRequest, ::Geyser::SubscribeReplayInfoResponse
      rpc :Ping, ::Geyser::PingRequest, ::Geyser::PongResponse
      rpc :GetLatestBlockhash, ::Geyser::GetLatestBlockhashRequest, ::Geyser::GetLatestBlockhashResponse
      rpc :GetBlockHeight, ::Geyser::GetBlockHeightRequest, ::Geyser::GetBlockHeightResponse
      rpc :GetSlot, ::Geyser::GetSlotRequest, ::Geyser::GetSlotResponse
      rpc :IsBlockhashValid, ::Geyser::IsBlockhashValidRequest, ::Geyser::IsBlockhashValidResponse
      rpc :GetVersion, ::Geyser::GetVersionRequest, ::Geyser::GetVersionResponse
    end

    Stub = Service.rpc_stub_class
  end
end
